export const STUDY_FIELDS = [
  "Computer Science",
  "Software Engineering",
  "Information Technology",
  "Information Systems",
  "Computer Engineering",
  "Electrical Engineering",
  "Electronics and Telecommunications Engineering",
  "Civil Engineering",
  "Mechanical Engineering",
  "Architecture",
  "Mathematics",
  "Statistics",
  "Physics",
  "Biology",
  "Chemistry",
  "Agriculture",
  "Veterinary Medicine",
  "Medicine and Surgery",
  "Nursing",
  "Pharmacy",
  "Public Health",
  "Business Administration",
  "Accounting",
  "Finance",
  "Economics",
  "Marketing",
  "Supply Chain and Logistics",
  "Law",
  "Education",
  "Psychology",
  "Journalism and Communication",
  "Hospitality and Tourism",
  "Environmental Science",
  "Geography and Urban Planning",
  "Development Studies",
  "Other / Not Listed",
] as const;

export const PERSONAL_INTERESTS = [
  "Building digital products",
  "Solving complex logic problems",
  "Analyzing data and patterns",
  "Protecting people and systems",
  "Creating visual and user experiences",
  "Understanding people and communication",
  "Running projects and business ideas",
  "Exploring how technology works",
] as const;

export type StudyField = (typeof STUDY_FIELDS)[number];
export type PersonalInterest = (typeof PERSONAL_INTERESTS)[number];
